### ISSUE TITLE
Only the main file is watched for hard reset

### ISSUE THREAD

**Issue by stomybexy** [yan-foto/electron-reload#10]
Hard reset is done for the main file only and not for change in the directory. In the code there is this: 
```js
let mainFile = path.join(appPath, config.main);
chokidar.watch(mainFile).on('change', () => {
```
I gess it should be this ?:
```js
chokidar.watch(appPath).on('change', () => {
```

**Comment by yan-foto** [comment]
It is only the main file that requires hard reset when changed, for everything else restarting the browser windows is enough in my opinion.

**Comment by stomybexy** [comment]
I'm testing this with angular2 and the browser reload give me the error 'Not allowed to load local resource: ' and the only workarround i've found is to do a hard reset on the app directory.

**Comment by yan-foto** [comment]
There are a number of reasons why that can happen (see [here]). But I don't consider this being related to this package or being a bug.
