### ISSUE TITLE
Reload fails: Not allowed to load local resource: data:text/html,chromewebdata

### ISSUE THREAD

**Issue by pamtbaau** [yan-foto/electron-reload#11]
**Without routing:**
I have cloned and build (using webpack) the template [Electrogram](https://github.com/onehungrymind/electrogram) and reloading work well out of the box. The Electrogram app is bootstrapped starting an AppComponent. No routing in this app.

When I replace the app folder by the [Quickstart](https://github.com/angular/quickstart) app from Angular and bootstrap the app from the AppModule the apps runs well and reloading works fine. This app does not have routing.

**With routing:**
When I replace the app folder by the [Tour of Heroes](https://angular.io/docs/ts/latest/tutorial/) tutorial app from Angular and bootstrap starting the top AppModule the app runs well. But..., when the app gets reloaded, the window remains blank and the following error occurs: "Not allowed to load local resource: data:text/html,chromewebdata".
When I bootstrap the app starting an AppComponent reloading works fine. Unfortunately routing does not work when bootstrapping from Component.

**Comment by yan-foto** [comment]
My experience with Angular (and/or any of the other frameworks you mentioned) is minimal to zero. I can only help if you have spotted a bug *limited* to `electron-reload` and have opted out other sources of the error.
