### ISSUE TITLE
Spell elecronReload correctly?

### ISSUE THREAD

**Issue by king-koda** [yan-foto/electron-reload#112]
**NOTE**: before openning an issue, please consult previous issues (both open and closed).

## What is the problem
How is the main function of this package mispelled? "elecronReload" ????

## How to reproduce
main.js, line 46, function elecronReload

**Comment by Deadreyo** [comment]
Thanks very much for mentioning this. I was wondering why it didn't work

**Comment by king-koda** [comment]
Not actually completed. Closing a ticket doesn't fix/ complete the issue.
