### ISSUE TITLE
Using inside webpack

### ISSUE THREAD

**Issue by michaeljota** [yan-foto/electron-reload#13]
hi! 

I'm trying to use this, in an Electron app, packaged with webpack, but as soon as the application start, it shows an error and don't load the windows content. 

![captura de pantalla 2](https://cloud.githubusercontent.com/assets/10507776/18561882/abd43e8e-7b4f-11e6-8314-982c2772af2e.png)

**Comment by yan-foto** [comment]
This doesn't seem to be related to this project.

**Comment by michaeljota** [comment]
What do you think can cause the error? I'm just adding the reloader to an existing project.

**Comment by yan-foto** [comment]
I have no idea. Stackoverflow might be the best place to ask.

**Comment by michaeljota** [comment]
I have an existing and working project, seed-like, and I'm just adding this module like you said `require('electron-reload')(__dirname);`
