### ISSUE TITLE
electron-prebuilt renamed

### ISSUE THREAD

**Issue by keverw** [yan-foto/electron-reload#16]
http://electron.atom.io/blog/2016/08/16/npm-install-electron

I went ahead and updated my project and removed prebuilt.

My code is:

```
require('electron-reload')(__dirname, {
        electron: require('electron')
    });
```

but I get "Electron could not be found. No hard resets for you!" when I start my app...

**Comment by yan-foto** [comment]
So you are only gonna have soft resets. I don't  get the question?

**Comment by keverw** [comment]
I changed `electron-prebuilt` to `electron` since they renamed the package. Before it gave hard resets.

**Comment by yan-foto** [comment]
`electron-prebuilt` still exists. I haven't yet played with the new one. I suppose you must have `electron` as local dependency so `require` actually finds it within your packages.

**Comment by keverw** [comment]
Yeah I had it installed locally. But I'm trying to the two package.json build now - I discovered that earlier before I started on that. But I think in the future I want to move to TypeScript so i'd have to recompile and restart anyways from my understanding. So soft restarts would probably be good enough for my needs.

**Comment by yan-foto** [comment]
I will check this later today and update the documentation. Thanks for the heads up and sorry for the initial misunderstanding!

**Comment by JBodkin** [comment]
Do you have an update on this?

**Comment by yan-foto** [comment]
@JBodkin not yet. pull requests are welcome!

**Comment by JBodkin** [comment]
Looks to be related to the way `require` works, when using the new package name

Previously the index.js file would be loaded returning the path to the executable, Instead the electron.asar is loaded.

I was able to work around this by providing a path to the index.js inside the module home instead.

```
require('electron-reload')(__dirname, {
  electron: require('${__dirname}/../../node_modules/electron')
})
```

**Comment by yan-foto** [comment]
I somehow suspected that `require(`electrol`)` doesn't return a file path, as `electron-reload` only verifies if the path to electron executable exists.

I'll take a look at it. I would try to find another way, as `require` (with or without your proposed solution) doesn't seem to be the right way to solve this problem in the long run.

Thanks for taking a look at it. 👍 .

**Comment by yan-foto** [comment]
Ok guys, I am going to close this issue. I took a look at the whole situation and realized that **obviously** you cannot `require` `electron` the way you do `electron-prebuilt`. I enhanced the `README` to address this issue. In short: use explicit path of `electron` binary instead of `require`!

**Comment by Peter-Gess** [comment]
Yan,

For context, I set up electron using this tutorial:  https://www.youtube.com/watch?v=jKzBJAowmGg

I used homebrew when installing node

I am getting the same message "Electron could not be found. No hard resets for you!" but I not getting any soft reset via electron-reload either.

Any idea what I am missing?

**Comment by yan-foto** [comment]
@Peter-Gess can depend on many things. You better should consult stackoverflow. Issues are preferably only for bugs.

**Comment by doncolio007** [comment]
Thanks @JBodkin. Fixed

**Comment by rachidsakara** [comment]
make sure that the **electron-reload** module is installed locally in your project, if not the case Visit your console and type:
`npm install electron-reload --save-dev`
Now in order to implement this module in your project; the main file (index.js or main.js), you have tree options:
Option 1:
`require('electron-reload')(__dirname)`
Option 2:
`require('electron-reload')(__dirname,
 {
  electron: require('${__dirname}/../../node_modules/electron')
})`
Option 3:
`require('electron-reload')(__dirname, {
    electron: require(`${__dirname}/node_modules/electron`)
})`

**Comment by Eshva** [comment]
@rachidsakara Thank you for comment. It helped me. But the only thing you need to fix are quotes. You should use ` not ' for interpolation.

For instance the proper version of Option 3 is:
```require('electron-reload')(__dirname, { electron: require(`${__dirname}/node_modules/electron`) })```

**Comment by rachidsakara** [comment]
Hi! Mike Eshva for the comment. well I think if copy it the command from
that answer it will works perfect on your coding Editor for instance
Sublime Text.

**Comment by rachidsakara** [comment]
Hi! Mike Eshva thanks for the comment. well I think if you copy any
command from that answer it will works perfect on your coding Editor for
instance Sublime Text.

**Comment by Eshva** [comment]
It will not. I've checked. For string interpolation you have to use backtick and you use single quote.

**Comment by anderm8** [comment]
Just FYI, backtick works, single quote did not for me.
