### ISSUE TITLE
Check app.relaunch out

### ISSUE THREAD

**Issue by yan-foto** [yan-foto/electron-reload#18]
https://github.com/electron/electron/blob/master/docs/api/app.md#apprelaunchoptions

**Comment by yan-foto** [comment]
This can be used instead of `child.spawn` to restart after `quit` or `exit` is called.

**Comment by HeilTec** [comment]
`child.spawn` supports inheriting stdio. 
This is needed for the application to stay attached to the console window.

In my preliminary tests this is not the case for `app.relaunch`
Perhaps this warrants an issue with electron?

As it stands I use this in my main.ts
``` javascript 
  import {spawn} from 'child_process'
  function relaunchApp(hardExit?:boolean,code?:number) {
    let child = spawn(
        path.join(__dirname,'..', 'node_modules', '.bin', 'electron'), 
        [app.getAppPath()],
        {
          detached: true,
          stdio: 'inherit'
        }
      )
    child.unref()
    hardExit ? app.exit(code) : app.quit()
  }
``` 
Both of the above possibilities keep the console attachment.

I tried to use `app.relaunch` like this:
``` javascript
  function relaunch() {
    app.relaunch({args: process.argv.slice(1)})
    app.quit()
  }
``` 
and that broke the connection.

**Comment by yan-foto** [comment]
Well done! I also don't see any indications in the docs that this would be possible. So I'd close this issue for now. Thanks for checking this out. 😄
