### ISSUE TITLE
why only watch main.js

### ISSUE THREAD

**Issue by hongxuanlee** [yan-foto/electron-reload#20]
https://github.com/yan-foto/electron-reload/blob/master/main.js#L43 
I hope to be able to watch other files change.

**Comment by yan-foto** [comment]
The line you highlighted regards hard reset. For everything else a soft-reset is done (see previous lines).

**Comment by hongxuanlee** [comment]
I hope other files can be  hard reset，You can analyze the dependency of main.js

**Comment by yan-foto** [comment]
Why do you need a hard reset for files other than `main.js`?

**Comment by hongxuanlee** [comment]
if `main.js` require `a.js` , I hope when  `a.js` change can be hard reset

**Comment by yan-foto** [comment]
It is not feasible IMHO to track all files `require`d by `main.js` for changes. If you have a concrete example, please provide, so we can discuss possible solutions.
