### ISSUE TITLE
Application flashes and exits when specifying electron binary on OSX

### ISSUE THREAD

**Issue by shanewignall** [yan-foto/electron-reload#25]
After specifying the explicit path of electron binary on OSX in the electron-reload config, the application flashes for a split second, then exits. Here's the code:
`require('electron-reload')(__dirname, {
  electron: path.join(__dirname, 'node_modules', 'electron', 'dist', 'Electron.app', 'Contents', 'MacOS','Electron'),
});`

Am I missing something?

**Comment by yan-foto** [comment]
Yes! I'm afraid you are missing the `README`:

> You could also use the (relatively) new electron package, but you should specify the path directly (no require!):
> 
> const path = require('path')
> 
> require('electron-reload')(__dirname, {
>   electron: path.join(__dirname, 'node_modules', '.bin', 'electron')
> });
