### ISSUE TITLE
[BUG] - Not allowed to load local resource: file://

### ISSUE THREAD

**Issue by nadavten** [yan-foto/electron-reload#27]
![image](https://cloud.githubusercontent.com/assets/17804204/22266219/cd383914-e287-11e6-9126-b3623f14f906.png)

**Comment by yan-foto** [comment]
Sorry but I must label this as *question* and refer you to stackoverflow.

If you'd like to file an issue, I'd need information, on your platform, electron version, etc. and how to reproduce the bug.
