### ISSUE TITLE
Crash on reload

### ISSUE THREAD

**Issue by UltraDosaaf** [yan-foto/electron-reload#28]
This works fine 
`require('electron-reload')(__dirname);`

But when I need full app restart, and try this
```
require('electron-reload')(__dirname, {
  electron: path.join(__dirname, 'node_modules', '.bin', 'electron')
});
```
Boom!
![1](https://cloud.githubusercontent.com/assets/25608313/22820519/3186c266-ef88-11e6-9550-76cef34e480d.PNG)

All files in their places
![2017-02-10_12-01-26](https://cloud.githubusercontent.com/assets/25608313/22820682/e780f834-ef88-11e6-99d1-14a3de9b0622.png)

**Comment by yan-foto** [comment]
see #26.
