### ISSUE TITLE
it does not work on osx

### ISSUE THREAD

**Issue by mikes01** [yan-foto/electron-reload#33]
Hello,

It does not work on osx for me. When I just require the electron:
`require('electron-reload')(__dirname, {
  electron: require('electron')
});`
I get the messsage: 

> Electron could not be found. No hard resets for you! 

So, I specify the electron path:
`require('electron-reload')(__dirname, {
  electron: path.join(__dirname, 'node_modules', '.bin', 'electron')
});`

With this config the app  flashes for a split second, then exits.

I've prepared demo: https://github.com/mikes01/electron-quick-start

**OS X El Capitain v10.11.5
electron v1.6.8
electron-reload v1.1.0**

i will appreciate your help with this issue.

**Comment by yan-foto** [comment]
Right from the readme:

> You could also use the (relatively) new electron package, but you should specify the path directly  (no require!):
>
> ```js
> const path = require('path')
> 
> require('electron-reload')(__dirname, {
>   electron: path.join(__dirname, 'node_modules', '.bin', 'electron')
> });
> ```

**Comment by yan-foto** [comment]
Reminds me of #25, but is not the same! I just checked it out on mac and it worked out fine. Seems to me that it is a setup problem and not a systematic bug. Please consult stackoverflow.

**Comment by yan-foto** [comment]
I'll let this issue stay open, until we can pinpoint the problem.

**Comment by digioak** [comment]
I just tried it on macOS and it does work for me.

**Comment by leozhao0709** [comment]
It also work for me.

**Comment by mikes01** [comment]
I've found the reason why the reload didn't work for me. I run the app by this command:
`electron main.js`
then the app flashes for a split second and exits.
When i run the app by:
`electron .`
It works as expected, the app runs and reloads on change.

**Comment by Tzikas** [comment]
`npm i electron -D` worked for me
