### ISSUE TITLE
Can we add an option for disable this module console log?

### ISSUE THREAD

**Issue by leozhao0709** [yan-foto/electron-reload#35]
Hi, I love this module, but each time when my multiple files changed, it will console log lots of 'changed'. Can we add a flag to disable the console to log this? Thanks.

**Comment by yan-foto** [comment]
I think this is something that I might have forgot to remove from production code! 😱 thanks for the headsup

**Comment by zakkor** [comment]
@yan-foto 
There is still this https://github.com/yan-foto/electron-reload/blob/abb9e27ab2ad38c1710eda159d0744c319610a31/main.js#L94
Can we maybe get an option to stop this? e.g.: `logging: false`

**Comment by manngo** [comment]
I was wondering about this myself. Is it something I can ignore, or do I need to fix something?

**Comment by Mackignacio** [comment]
I think this only happens when you add the options for electron and the path the you put doesn't exist as seen below. 

![image](https://user-images.githubusercontent.com/12345233/62425708-c855c480-b70e-11e9-95ca-22f87b93d7bf.png)

**Comment by dignite** [comment]
Hi! This also happens when there is no `options.electron` property set. In that case, I think it should not log, as I have opted out from having a hard reset on changes to `main.js`.

**Comment by Mackignacio** [comment]
@dignite  Yes you are right. If there is no option available the log should not log therefore we can add an if statement checking for the `eXecutable` if that is not undefined. If `eXecutable` is undefined we will just do nothing.

```javascript
if (eXecutable && fs.existsSync(eXecutable)) {
    const hardWatcher = chokidar.watch(mainFile, Object.assign({ ignored: [ignoredPaths] }, options))

    if (options.forceHardReset === true) {
      // Watch every file for hard reset and not only the main file
      hardWatcher.add(glob)
      // Stop our default soft reset
      watcher.close()
    }

    hardWatcher.once('change', hardResetHandler)
  } else {

   // Only shows the log if eXecutable is not undefined
    if (eXecutable) {
      console.log('Electron could not be found. No hard resets for you!')
    }
  }
```
