### ISSUE TITLE
how to ignore files / directories

### ISSUE THREAD

**Issue by zombieleet** [yan-foto/electron-reload#36]
is there any option of ignoring files / directory that is files or directory change that will not trigger reload

**Comment by yan-foto** [comment]
This is not an issue. Please read the [API](https://github.com/yan-foto/electron-reload#api)

**Comment by wolfiex** [comment]
ISSUE : API section not sufficiently clear or descriptive. 

What does `options (optional): chokidar options plus electron property pointing to electron executables.` mean?

**Comment by yan-foto** [comment]
Literally quoting here:

```
default: {ignored: /node_modules|[\/\\]\./}
```

and when you check [chokidar docs](https://www.npmjs.com/package/chokidar#path-filtering) it is self explanatory.
