### ISSUE TITLE
Allow option to reload to original file path or specified URL (e.g. vs refresh)

### ISSUE THREAD

**Issue by jhillhouse92** [yan-foto/electron-reload#44]
I have a use case where I'm using this with Angular 5 and the PathLocationStrategy. The path location strategy uses HTML5 url push to put urls in the format /home instead of /#home (hash strategy). When using this within electron and it refreshes because of changes the browser tries to actually load /home from the file path.

**Comment by yan-foto** [comment]
The current reloading approach is simply to [tell electron to reload the browser window](https://github.com/yan-foto/electron-reload/blob/v1.2.2/main.js#L33). What is suggested here requires keeping track of the original URL of each `BrowserWindow` and [reload to that URL](https://electronjs.org/docs/api/web-contents#contentsloadurlurl-options). Maybe hard resetting would be the simplest hack to have the same effect!

I am reluctant to add such a feature for a specific use case, which might not be relevant for everyone. **Or** we find an elegant solution which doesn't add such overhead.

**Comment by yan-foto** [comment]
Too old, too specific! Closing.
