### ISSUE TITLE
Hard reset not working on windows

### ISSUE THREAD

**Issue by aammfe** [yan-foto/electron-reload#53]
Hard reset not working on windows
 "electron-reload": "^1.3.0",

form my investigation

`const _path = path.join(
      __dirname,
      '../../',
      'node_modules',
      '.bin',
      'electron'
    );
`

but when append **.cmd** it work.
`const _path = path.join(
      __dirname,
      '../../',
      'node_modules',
      '.bin',
      'electron.cmd'
    );
`

is its suppose to work like this ..?
if yes then please describe it in doc. Thanx :)

![image](https://user-images.githubusercontent.com/11896817/49258325-def89d00-f456-11e8-8457-f8184acc916f.png)

**Comment by yan-foto** [comment]
Same as #26
