### ISSUE TITLE
Main file is ignored

### ISSUE THREAD

**Issue by mscoobby** [yan-foto/electron-reload#57]
## What is the problem
The main files is included in the ignored paths and therefore the watcher ignores is resulting in no hard resets at all.

## How to reproduce
Import the library in any Electron project, run the app and make changes on the main file without setting the `forceHardReset` flag

## Additional information
`"electron-reload": "~1.4.0",`
`"electron": "~5.0.6",`

**Comment by yan-foto** [comment]
The main file is in ignored paths both with and without forced hard reset, but it seems that `chokidar` behaves differently. Does hard reset work for the main file when `forceHardReset` is set to `true`? On which OS are you?

**Comment by yan-foto** [comment]
Is this related to #26 ?

**Comment by mscoobby** [comment]
If I set the `forceHardReset` to `true` it works for all files. I'm using Windows but removing `mainFile` from the ignored paths fixes the issue. No it's not related to #26 since it finds the `appPath` and `mainFile` correctly.

**Comment by yan-foto** [comment]
This is really interesting, `forceHardReset` does not change the ignored path, but solves the problem. 🤔

**Comment by yan-foto** [comment]
Try the changes on [`develop`](https://github.com/yan-foto/electron-reload/commit/269f1d6d14fd6e0581ef9e7989ed0a3418da48ae) branch.

**Comment by mscoobby** [comment]
It adds the `glob` which most likely overwrites the specific path.

**Comment by yan-foto** [comment]
Adding just extends the list of files to be watched. It shouldn't change the ignored list.

**Comment by mscoobby** [comment]
> Try the changes on [`develop`](https://github.com/yan-foto/electron-reload/commit/269f1d6d14fd6e0581ef9e7989ed0a3418da48ae) branch.

I don't have the repository cloned. But removing the `mainFile` from the ignored paths actually triggers the hard reset.

**Comment by yan-foto** [comment]
You don't need the repository cloned, just run `npm i https://github.com/yan-foto/electron-reload.git#develop` and `require` it as usual and see if everything works.

**Comment by mscoobby** [comment]
> You don't need the repository cloned, just run `npm i https://github.com/yan-foto/electron-reload.git#develop` and `require` it as usual and see if everything works.

Yes I've just cloned it and run the app. Hard reset works without any modifications and it spawns only 1 process.

**Comment by yan-foto** [comment]
Alright! I'll release a new version.

**Comment by mscoobby** [comment]
> Alright, thanks! I'll release a new version.

Perfect! When do you expect to release it?

**Comment by yan-foto** [comment]
ASAP. I've got a lot to take care of.
