### ISSUE TITLE
Reload a packaged electron app using electron-reload

### ISSUE THREAD

**Issue by saadsaeed01** [yan-foto/electron-reload#59]
Hello,
I have electron app which I am running on a Linux system and I have packaged it using electron packager. What i want to do is reload my app whenever there is a change in the directory that contains the package. Does electron-reload provide this functionality (i.e detecting changes in the directory that contains the packaged binaries)

**Comment by yan-foto** [comment]
Theoretically yes, you can pass any path that you want to `electron-reload`, but I think you should some other packages such as `chokidar` to track changes on the file system.
