### ISSUE TITLE
Project could upgrade to Chokidar 3

### ISSUE THREAD

**Issue by erickzhao** [yan-foto/electron-reload#63]
The `chokidar` package on NPM recently got a major version bump from 2 to 3. Although there haven't been many API changes from v2 (see [Changelog](https://github.com/paulmillr/chokidar/blob/master/.github/full_changelog.md)), Chokidar v3 drastically reduces the size of `node_modules` and enforces a minimum of Node 8.

See [blog post](https://paulmillr.com/posts/chokidar-3-save-32tb-of-traffic/):

> Let’s compare npm install on a clean machine for v2 and v3:
> 
> Chokidar v2:
> 
> Installation time: 7.753 sec
> Consumes 3.195mb of traffic (3.03mb down, 165kb up) and makes 46 network connections
> Creates 201 packages from 130 contributors and audits 2113 packages
> node_modules file count: 1,251 (484 *.js)
> node_modules size: 8.3Mb
> Chokidar v3:
> 
> Installation time: 1.575 sec (4.9x faster)
> Consumes 352Kb of traffic (9x less) (329kb down, 23kb up) and makes 16 network connections
> Creates 15 packages (13x less) from 20 contributors and audits 19 packages
> node_modules file count: 79 (26 *.js) (15.8x less)
> node_modules size: 496Kb (16.7x less)

**Comment by yan-foto** [comment]
Thanks for letting me. Chokidar being bloated always annoyed the hell out of me! I'll upgrade in the next release.
