### ISSUE TITLE
Typescript Definition

### ISSUE THREAD

**Issue by macign** [yan-foto/electron-reload#65]
I notice that some developers requested a typescript definition.  As seen on issue #22 and #60. I submitted a pull request #64 with regards to this issue. I hope I can help. Thanks.

**Comment by Mackignacio** [comment]
@yan-foto  I suggest the better way is to only have a `.d.ts` file inside the library without converting the whole code base to typescript. I can make a simple npm script just for generating those declaration files and add them on the `package.json` file. See this [blog ](https://medium.com/razroo/what-are-declaration-files-in-typescript-476c1c06f353) on how `moment.js` add declaration files for their library

**Comment by Mackignacio** [comment]
@yan-foto this is the sample main.d.ts file generated from a script I made. With the script you don't need to convert your codebase to typescript just add a JSdoc on the module.exports and it will generate the `.d.ts.` file for you. Below is the code inside the `main.d.ts` file that typescript will read when they add electron-reload as a dependency.

```javascript
declare function _exports(glob: string | string[], options?: {
    persistent?: boolean | undefined;
    ignored?: any;
    ignoreInitial?: boolean | undefined;
    followSymlinks?: boolean | undefined;
    cwd?: string | undefined;
    disableGlobbing?: boolean | undefined;
    usePolling?: boolean | undefined;
    useFsEvents?: boolean | undefined;
    alwaysStat?: boolean | undefined;
    depth?: number | undefined;
    interval?: number | undefined;
    binaryInterval?: number | undefined;
    ignorePermissionErrors?: boolean | undefined;
    atomic?: number | boolean | undefined;
    awaitWriteFinish?: any;
} | undefined): void;
export = _exports;
```

**Comment by wapenshaw** [comment]
hey @Mackignacio Thanks so much for the typings!!

For anyone who came here looking for the solution. 

1. Create a file main.d.ts in your `/node_modules/electron-reload/`  (where electron-reload's main.js file is)
2. Paste in the typings mentioned here https://github.com/yan-foto/electron-reload/issues/65#issuecomment-598023775 into the `main.d.ts` file
3. In your application's `main.ts` file you can then use electron-reload like this

```ts
import electronReload from 'electron-reload'
const uiPath = path.join(__dirname, '..', 'ui');
electronReload(uiPath)
```
Here in my project, I split electron and renderer code into main and ui respectively so I have to go up one folder and watch the ui folder where my webpack outputs the react compiled code. If its not reloading, debug and make sure your `uiPath` is set right.

I am using this on electron v11.0.1 with typescript v4.05 and its working.

**Comment by Mackignacio** [comment]
@wapenshaw You're welcome glad that I could help.

**Comment by xinaesthete** [comment]
@Mackignacio's patch seems promising, but it would also be reassuring if @yan-foto could review the PR as it might save people doing things like edit `node_modules` on one system, then forget it about months later when their build fails somewhere else...

Cheers

**Comment by yan-foto** [comment]
@xinaesthete yes, I really need someone with typescript expertise to review the code (i.e., not me!). Last time I wanted to merge code I found out that half of the functionality was removed (don't ask me why!).

So I would appreciate anyone that can review this code so I can merge it.

**Comment by xinaesthete** [comment]
Hi @yan-foto, appreciate the quick reply.  I'm not sure whether I'll use this yet, although may look it over shortly... just setting up a new project and haven't quite got that part of the config nailed down.

Certainly sympathetic to your motives for creating this!

No promises but I might try to review if I get time.
