### ISSUE TITLE
Runtime error: cannot find module 'electron-reload'

### ISSUE THREAD

**Issue by Serkonda** [yan-foto/electron-reload#73]
## What is the problem
If starting an distributed app that uses electron-reload, an error occurs, that the module cannot be found.

## How to reproduce
Deploy and open an empty electron app, that uses electron-reload.

## Desired Solution
Though this is easy to prevent, by adding a check for development environment, I would highly appreciate to see a hint in the documentation similar to this:

```javascript
if (process.env.NODE_ENV === 'development') {
    // require(...);
}
```

**Comment by yan-foto** [comment]
If you don't have `electron-reload` you'll get an error. What's the problem?

**Comment by Serkonda** [comment]
There is no need to include this in a production build, as there are no changes that could be reloaded.
But if you exclude it, the above described error happens.
I only would like to have this mentioned in the _Usage_ part of the ```README```.

**Comment by yan-foto** [comment]
I'd leave to the developers to decide on how they want to handle such cases. Thanks for the suggestion though!
