### ISSUE TITLE
How to watch for required files change ?

### ISSUE THREAD

**Issue by shmox75** [yan-foto/electron-reload#76]
I need to watch for my own created required files

for example in my main index.js file I have
```
const bootstrap = require('./electron/bootstrap');

bootstrap.init()
```

I want to watch changes of file electron/bootstrap.js is it possible ?

EDIT: 
I tried with forceHardReset: true it works but how can i do it without hard reset ?
I need to watch for folder called "electron" inside my __dirname so I tried with this but it doesn't work:

require('electron-reload')(__dirname, {
      electron: require(`${__dirname}/node_modules/electron`),
      hardResetMethod: 'exit',
      //forceHardReset: true,
      argv: ['--serve'],
      chokidar: {
        paths: [`${__dirname}/electron/*.js`]
      }
    });

how to set chokidar to watch in my electron/*.js path ? thanks

**Comment by yan-foto** [comment]
It seems to be trouble shooting question, which I cannot answer!
