### ISSUE TITLE
Add option for file arguments

### ISSUE THREAD

**Issue by KonradLL** [yan-foto/electron-reload#87]
Currently the argv option sets arguments between the executable and the file, `electron ...argv file`. This makes it impossible to pass argument to the app itself, `file ...args`, on reload. I currently set multiple flags depending on the needs and see no way of doing this. 

Could an option be added to that allows for specifying arguments to be passed to the app, something like appArgv. This should then result in the following command: `electron ..argv file ...appArgv`.

**Comment by yan-foto** [comment]
Good point! Please give us some time to take care of it.

Thanks for reporting.
