### ISSUE TITLE
Cannot read property 'filename' of  undefined

### ISSUE THREAD

**Issue by christophbuehler** [yan-foto/electron-reload#90]
Occurs when using webpack with TS-Loader.
My webpack.config.js:
```
module.exports = {
  target: "electron-main",
  entry: "./electron/main.ts",
  output: {
    filename: "main.js",
    path: path.resolve(__dirname, "./"),
  },
  plugins: [
    ElectronReloadPlugin(),
  ],
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        use: {
          loader: "ts-loader",
          options: {
            configFile: "electron/tsconfig.json",
          },
        },
        exclude: /node_modules/,
      },
    ],
  },
  resolve: {
    extensions: [".tsx", ".ts", ".js"],
  },
  node: {
    __dirname: false,
    __filename: false,
  },
};
```

**Comment by yan-foto** [comment]
We already discussed this in #66. The bottom line is: **there is no valid use case for packing `electron-reload` with electron reload`.

**Comment by christophbuehler** [comment]
I am using TypeScript for my Electron main process code.

**Comment by christophbuehler** [comment]
You are right, same fix. Is there a timeline on when this fix will be introduced?

**Comment by yan-foto** [comment]
Sorry for quickly closing your issue and PR. I have little to no time to maintain this repository and am looking for a maintainer, so I cannot tell when everything moves forward. If I get enough time, I'll review and merge the blocking PR.

**Comment by christophbuehler** [comment]
Not a problem, thanks for the quick response.

**Comment by yan-foto** [comment]
If you are interested in contributing to this project and are using TS, you could give try #79 and make sure if everything works well. Merging that would also solve your problem and would be a really great help to me. :grinning:
