### ISSUE TITLE
Chokidar error on windows

### ISSUE THREAD

**Issue by belqit** [yan-foto/electron-reload#93]
```
require('electron-reload')(__dirname, {
	electron: require('electron-prebuilt')
});
```

![image](https://user-images.githubusercontent.com/44238749/106009320-7cdc6680-60b8-11eb-8873-7501d1a826f6.png)

**Comment by yan-foto** [comment]
I updated the README and removed the usage of `electron-prebuilt` altogether. Stick to the `electron` package and you'll be good to go!
