### ISSUE TITLE
Uncaught TypeError: Cannot read property 'app' of undefined` in `electron-reload/main.js

### ISSUE THREAD

**Issue by i-panov** [yan-foto/electron-reload#94]
## What is the problem
`Uncaught TypeError: Cannot read property 'app' of undefined` in `electron-reload/main.js`

## How to reproduce
```
const { app } = Vue.$electron
require('electron-reload')(__dirname)
```

## Additional information
Windows 10, Node 15.8.0, Electron 2.0.4

**Comment by yan-foto** [comment]
This is not related to this project. I suppose you are doing something wrong with `Vue`.
