### ISSUE TITLE
App reloads on save but changes are not applied

### ISSUE THREAD

**Issue by andreav94** [yan-foto/electron-reload#95]
With the following code i can get the app to reload on save, but the changes are not applied.

```
 require('electron-reload')(__dirname +"../app/", {
    electron: path.join(__dirname, '..', 'node_modules', '.bin', 'electron'),
  })
```
I have and application with main, renderer, and worker process builded with webpack and electron-builder on MacOS.
Webpack builds the typescript project in the /build directory and the src files are in the /app directory. I presume the path in the above scripts are correct, since the app is reloading on save, but i think electron-reload is not rebuilding the changed files in /app dir, so the files run by electron in the /build file are still the same.

I run the app with electron /build/main.js

If i'm correct, how to make electron-reload rebuild the files?

**Comment by yan-foto** [comment]
Check out the other issues. I don't understand why do people insist on using this module with webpack, that is to use a development module in production software! If you need to reload the content in your production software, take a look at the source code and copy what you deem necessary to your code base.
