### ISSUE TITLE
Use dinamic `main` instead of index.js

### ISSUE THREAD

**Issue by LeonardoRick** [yan-foto/electron-reload#96]
## What is the problem
I'm using `main.dev.js` and `main.prod.js` to setup two environments. To start electron its ok to use `electron main.dev.js`, but when its reload the library looks for a main input and its not found. Is there a way to dinamic set the enter file in order to use multiple environments with your library?

## How to reproduce
basicaly this setup: https://stackoverflow.com/questions/53921403/how-to-build-different-versions-with-environment-variables

**Comment by yan-foto** [comment]
Yes you can. Read the environment variable and set `paths` in `electron_reload(paths, options)` to any value you want. Don't expect the software to automagically adapt to all marginal cases!
